#######################################################################
### CXX: The name of the c++ compiler
### ROOTDIR: The installation directory of the tool
### LINK: Additional link directives
### INCL: Additional include directives
CXX = g++
LINK =
INCL =
CFLAGS = -O4 -fopt-info -fopenmp  -fPIC  -Ofast -fopt-info-vec -ffast-math 
ROOTDIR = /home/Desktop/TsoulosColab/GenClass/

