#######################################################################
### CXX: The name of the c++ compiler
### ROOTDIR: The installation directory of the tool
### LINK: Additional link directives
### INCL: Additional include directives
CXX = g++
LINK = 
INCL =
CFLAGS =
ROOTDIR = /home/sheridan/GenClass/

